[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/marketing/**"]

[deploy]
startCommand = "npx serve dist -s -l ${PORT:-3000}"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
